repos:
- repo: https://github.com/psf/black
  rev: 24.8.0  # Use the latest stable version (check for updates)
  hooks:
  - id: black
    stages: [pre-commit]
- repo: https://github.com/pycqa/flake8
  rev: 7.1.0
  hooks:
  - id: flake8
    stages: [pre-commit]
- repo: local
  hooks:
  - id: freeze-requirements
    name: freeze requirements.txt from venv
    entry: bash scripts/update-requirements.sh
    language: system
    pass_filenames: false
    always_run: true
    stages: [pre-commit]
- repo: https://github.com/pycqa/isort
  rev: 6.0.1
  hooks:
    - id: isort
      name: isort
      args: [--profile=black, --line-length=80]
      stages: [pre-commit]