site_name: Minitrade
repo_url: https://github.com/dodid/minitrade

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - mkdocs-click
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

dev_addr: "127.0.0.1:8888"

extra:
  analytics:
    provider: google
    property: G-HK9C9K1N4Q

nav:
  - Home:
      - index.md
      - install.md
      - cli.md
      - Compatibility: compatibility.md
  - "API Reference":
      - backtest.md
      - datasource.md
      - broker.md
      - trader.md
  - "Examples":
      - "Original from Backtesting.py":
          - examples/README.md
          - examples/Quick Start User Guide.ipynb
          - examples/Strategies Library.ipynb
          - examples/Multiple Time Frames.ipynb
          - examples/Parameter Heatmap & Optimization.ipynb
          - examples/Trading with Machine Learning.ipynb
