site_name: Minitrade

theme:
  name: material
  # features:
  #   - navigation.expand

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter

markdown_extensions:
  - mkdocs-click

dev_addr: "127.0.0.1:8888"

watch:
  - "minitrade/trader"

nav:
  - index.md
  - install.md
  - cli.md
  - "API Reference":
      - backtest.md
      - datasource.md
      - broker.md
      - trader.md
  - "Examples from Backtesting.py":
      - examples/README.md
      - examples/Quick Start User Guide.ipynb
      - examples/Strategies Library.ipynb
      - examples/Multiple Time Frames.ipynb
      - examples/Parameter Heatmap & Optimization.ipynb
      - examples/Trading with Machine Learning.ipynb
