[tool.poetry]
name = "minitrade"
version = "0.1.19"
description = "A personal trading system"
authors = ["Wei Wu <dodid@outlook.com>"]
readme = "README.md"
license = "AGPL-3.0-or-later"
repository = "https://github.com/dodid/minitrade"
homepage = "https://minitrade.github.io/"
documentation = "https://minitrade.github.io/docs/"
keywords = ["trading", "algorithmic-trading", "backtesting", "interactive-brokers"]


[tool.poetry.dependencies]
python = "3.10.*"
streamlit = "^1.15.2"
pandas = "^1.5.2"
numpy = "^1.23.5"
apscheduler = "^3.9.1.post1"
watchdog = "^2.2.0"
pandas-ta = "^0.3.14b0"
bokeh = "^2.4.3"
yfinance = "^0.1.93"
matplotlib = "^3.6.2"
seaborn = "^0.12.1"
tqdm = "^4.64.1"
pydantic = "^1.10.2"
nanoid = "^2.0.0"
fastapi = {extras = ["all"], version = "^0.92.0"}
requests = "^2.28.1"
selenium = "^4.7.2"
psutil = "^5.9.4"
pyyaml = "^6.0"
pypika = "^0.48.9"
click = "^8.1.3"
mailjet-rest = "^1.3.4"
scikit-learn = "^1.2.1"
scipy = "^1.10.0"
scikit-optimize = { git = "https://github.com/dodid/scikit-optimize.git", branch = "master" }


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.0"
pytest = "^7.2.0"
sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.1.1"
jupyter = "^1.0.0"
notebook = "^6.5.2"
vprof = "^0.38"


[tool.poetry.scripts]
minitrade = 'minitrade.cli:mtcli'


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
