name: build_docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10.10
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material==8.5.11
      - run: pip install "mkdocstrings[python]"
      - run: pip install mkdocs-click
      - run: pip install mkdocs-jupyter==0.22.0
      - run: mkdocs gh-deploy --force --no-history
